services:
  portfolio_main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_main
    restart: unless-stopped
    environment:
      PYTHON_GIL: ${PYTHON_GIL:-0}
      DEPLOYMENT_TYPE: ${DEPLOYMENT_TYPE:?DEPLOYMENT_TYPE is required}
    networks:
      - default
    env_file:
      - path: .env
        required: false

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: portfolio_caddy
    restart: unless-stopped
    ports:
      - "127.0.0.1:7011:7011"
    networks:
      - default
      - gatekeeper
      - cloudflared-tunnel

networks:
  default:
  gatekeeper:
    external: true
    name: gatekeeper_default
  cloudflared-tunnel:
    external: true
    name: cloudflared-tunnel_default
