services:
  portfolio_main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_main
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PYTHON_GIL: ${PYTHON_GIL:-0}
      DEPLOYMENT_TYPE: ${DEPLOYMENT_TYPE:?DEPLOYMENT_TYPE is required}
      SECRET_KEY: ${SECRET_KEY:?SECRET_KEY is required}
    networks:
      - default
      - tailscale-proxy
    env_file:
      - path: .env
        required: false

networks:
  default:
  tailscale-proxy:
    external: true
    name: tailscale-network_proxy_network
